from __future__ import annotations

import math
import time

import torch
from torch import nn

from .basis import random_orthogonal_basis, svd_basis
from .common import AdapterLinearBase, BasisKind, check_rank


class TinyLoRALinear(AdapterLinearBase):
    """TinyLoRA: LoRA-XS basis with R generated by a tiny trainable vector.

    R(v) = sum_i v_i P_i, where P_i are fixed random matrices by default.
    Passing the same shared_vector to many modules implements TinyLoRA tying.
    If trainable_projection=True, the random projection tensor P also becomes
    trainable; this intentionally changes both parameter count and capacity.
    """

    adapter_name = "tinylora"

    def __init__(
        self,
        linear: nn.Linear,
        rank: int,
        projection_dim: int = 1,
        alpha: float | None = None,
        basis: BasisKind = "svd_top",
        seed: int = 0,
        shared_vector: nn.Parameter | None = None,
        trainable_projection: bool = False,
    ) -> None:
        check_rank(rank, linear.out_features, linear.in_features)
        if projection_dim < 1:
            raise ValueError(f"projection_dim must be positive, got {projection_dim}")
        started = time.perf_counter()
        super().__init__(linear, alpha=alpha if alpha is not None else 1.0)
        self.rank = rank
        self.projection_dim = projection_dim
        self.basis = basis
        if basis in {"svd_top", "svd_bottom"}:
            left, right = svd_basis(linear.weight, rank, basis=basis)
        elif basis == "random_orthogonal":
            left, right = random_orthogonal_basis(
                linear.out_features,
                linear.in_features,
                rank,
                device=linear.weight.device,
                dtype=linear.weight.dtype,
                seed=seed,
            )
        else:
            raise ValueError(f"unsupported basis {basis}")
        self.register_buffer("left_basis", left)
        self.register_buffer("right_basis", right)

        generator = torch.Generator(device="cpu")
        generator.manual_seed(seed + 17 * projection_dim + 31 * rank)
        projection = torch.randn(projection_dim, rank, rank, generator=generator) / math.sqrt(rank * rank)
        projection = projection.to(device=linear.weight.device, dtype=linear.weight.dtype)
        if trainable_projection:
            self.projection = nn.Parameter(projection)
        else:
            self.register_buffer("projection", projection)

        if shared_vector is None:
            self.v = nn.Parameter(torch.zeros(projection_dim, device=linear.weight.device, dtype=linear.weight.dtype))
        else:
            if shared_vector.numel() != projection_dim:
                raise ValueError("shared_vector size must equal projection_dim")
            self.v = shared_vector
        self.svd_time_seconds = time.perf_counter() - started if basis.startswith("svd") else 0.0

    def tiny_R(self) -> torch.Tensor:
        return torch.einsum("u,uij->ij", self.v.to(self.projection.dtype), self.projection)

    def delta_weight(self) -> torch.Tensor:
        return self.left_basis @ self.tiny_R() @ self.right_basis
